create table "public"."achievement" (
    "id" bigint generated by default as identity not null,
    "user_id" text not null,
    "i_am_villager" smallint not null default '0'::smallint,
    "i_am_werewolf" smallint not null default '0'::smallint,
    "i_am_guard" smallint not null default '0'::smallint,
    "i_am_hunter" smallint not null default '0'::smallint,
    "i_am_witcher" smallint not null default '0'::smallint,
    "i_am_predictor" smallint not null default '0'::smallint,
    "vote_to_kill" smallint not null default '0'::smallint,
    "nightmare" smallint not null default '0'::smallint,
    "suicided" smallint not null default '0'::smallint,
    "good_werewolf" smallint not null default '0'::smallint,
    "god_of_gamblers" smallint not null default '0'::smallint,
    "selfless" smallint not null default '0'::smallint,
    "protected" smallint not null default '0'::smallint,
    "bodhisattva" smallint not null default '0'::smallint,
    "poison_master" smallint not null default '0'::smallint,
    "nice_shot" smallint not null default '0'::smallint,
    "bad_shot" smallint not null default '0'::smallint,
    "no_shot" smallint not null default '0'::smallint,
    "voyeur" smallint not null default '0'::smallint,
    "killed_by_vote" smallint not null default '0'::smallint,
    "dead_on_the_first_day" smallint not null default '0'::smallint,
    "last_of_survivor" smallint not null default '0'::smallint,
    "lonely_werewolf" smallint not null default '0'::smallint,
    "fratricidal_fighting" smallint not null default '0'::smallint,
    "traitor" smallint not null default '0'::smallint
);


alter table "public"."achievement" enable row level security;

CREATE UNIQUE INDEX achievement_pkey ON public.achievement USING btree (id);

CREATE UNIQUE INDEX "achievement_user_id_key" ON public.achievement USING btree ("user_id");

alter table "public"."achievement" add constraint "achievement_pkey" PRIMARY KEY using index "achievement_pkey";

alter table "public"."achievement" add constraint "achievement_user_id_key" UNIQUE using index "achievement_user_id_key";

grant delete on table "public"."achievement" to "anon";

grant insert on table "public"."achievement" to "anon";

grant references on table "public"."achievement" to "anon";

grant select on table "public"."achievement" to "anon";

grant trigger on table "public"."achievement" to "anon";

grant truncate on table "public"."achievement" to "anon";

grant update on table "public"."achievement" to "anon";

grant delete on table "public"."achievement" to "authenticated";

grant insert on table "public"."achievement" to "authenticated";

grant references on table "public"."achievement" to "authenticated";

grant select on table "public"."achievement" to "authenticated";

grant trigger on table "public"."achievement" to "authenticated";

grant truncate on table "public"."achievement" to "authenticated";

grant update on table "public"."achievement" to "authenticated";

grant delete on table "public"."achievement" to "service_role";

grant insert on table "public"."achievement" to "service_role";

grant references on table "public"."achievement" to "service_role";

grant select on table "public"."achievement" to "service_role";

grant trigger on table "public"."achievement" to "service_role";

grant truncate on table "public"."achievement" to "service_role";

grant update on table "public"."achievement" to "service_role";
