create table
  public.games (
    id bigint generated by default as identity,
    "groupId" text not null,
    type text not null,
    status smallint not null,
    data json null,
    updated_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now(),
    constraint games_pkey primary key (id)
  ) tablespace pg_default;

-- Enable MODDATETIME extension
create extension if not exists moddatetime schema extensions;

-- This will set the `updated_at` column on every update
create trigger handle_updated_at before update on games
  for each row execute procedure moddatetime (updated_at);

alter table "games" enable row level security;